### ISSUE TITLE
AttributeError: 'PixelBuf' object has no attribute '_transmit'

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#4682]
When resuming from light sleep, the code crashes with this error:
```
Traceback (most recent call last):
  File "code.py", line 44, in <module>
  File "/lib/adafruit_funhouse/__init__.py", line 122, in enter_light_sleep
AttributeError: 'PixelBuf' object has no attribute '_transmit'
```

I'm not sure what happened since I had previously tested this, but will fix it as soon as I can figure out what is going on.

**Comment by makermelissa** [comment]
According to @kattni, this issue has been reportedly been seen on the Saola and QT Py M0 Haxpress. I observed in on the FunHouse.

**Comment by anecdata** [comment]
This appeared for me after 7.0.0 (Saola, but suspect it isn't port-dependent), never saw it in 6.2.0 on any device.

**Comment by Neradoc** [comment]
`fill` does not cause the bug in the same version I encountered it:
```py
Adafruit CircuitPython 7.0.0-alpha.1-844-g9e183bbbb on 2021-04-27; Adafruit QT Py M0 Haxpress with samd21e18
>>> import board
>>> import neopixel
>>> pix = neopixel.NeoPixel(board.NEOPIXEL,1)
>>> pix.fill((0,255,0))
```

**Comment by hierophect** [comment]
I'm running into this now that all the 6.2 mpy files are deprecated for 7.0.0

**Comment by jerryneedell** [comment]
FYI -- I was able to "workaround" this but using adafruit_pypixelbuf on adafruit_dotstar instead of _pixelbuf
That is, in adafruit_dotstart, just import adafruit_pypixelbuf as _pixelbuf
It now works with 7.0.0 (tip of main)

**Comment by dunkmann00** [comment]
This must have something to do with merging the newer versions of Micropython (#4646, #4649). '_transmit' exists in the Neopixel and Dotstar subclasses, not in _Pixelbuf, which is the superclass. So for some reason instead of searching the subclass type for the transmit function and then searching the _Pixelbuf type, it would seem Circuitpython is only searching _Pixelbuf. 

This would also support why 'fill' would work, as it is a function from _Pixelbuf. It is interesting using adafruit_pypixelbuf works, since that would indicate the problem has to do with subclassing a native type from Circuitpython, but not something written in Python.

If @tannewt has plans to continue to merge the newer versions of Micropython perhaps this will be fixed in one of those?

**Comment by makermelissa** [comment]
Makes sense. Last I heard he is planning to continue. If it doesn't fix it, then it would make more sense to address this issue after that is finished so it doesn't break again.

**Comment by kattni** [comment]
Yes, the plan is to merge though the current version. As there is no 7.0.0 release yet, I agree we should wait to address this issue until we're done merging MicroPython.

**Comment by tannewt** [comment]
@jepler Is looking at this. `_transmit` is usually on the subclass (not PixelBuf) so it's likely a bug with the attribute lookup.

**Comment by jerryneedell** [comment]
I believe this was resolved by #4688 -- OK to close?
