### ISSUE TITLE
Error running circuitpython_setboard in python 3.14

### ISSUE THREAD

**Issue by alec-bike** [adafruit/circuitpython#10660]
### CircuitPython version and board name

```python
circuitpython-stubs 10.0.0 on macos 26.
```

### Code/REPL

```python
N/A
```

### Behavior

N/A

### Description

Just updated to python 3.14 and got the following error:

```sh
❯ uv run circuitpython_setboard feather_m4_can

Traceback (most recent call last):
  File ".venv/bin/circuitpython_setboard", line 4, in <module>
    from circuitpython_setboard import set_board
  File ".venv/lib/python3.14/site-packages/circuitpython_setboard/__init__.py", line 15, in <module>
    from importlib.abc import Traversable
ImportError: cannot import name 'Traversable' from 'importlib.abc' (cpython-3.14.0-macos-aarch64-none/lib/python3.14/importlib/abc.py)
```

Works fine with python 3.13.

**Comment by dhalbert** [comment]
From the 3.14 release notes:

> importlib.abc
> Remove deprecated [importlib.abc](https://docs.python.org/3.14/library/importlib.html#module-importlib.abc) classes:
> 
> ResourceReader (use [TraversableResources](https://docs.python.org/3.14/library/importlib.resources.abc.html#importlib.resources.abc.TraversableResources))
> 
> Traversable (use [Traversable](https://docs.python.org/3.14/library/importlib.resources.abc.html#importlib.resources.abc.Traversable))
> 
> TraversableResources (use [TraversableResources](https://docs.python.org/3.14/library/importlib.resources.abc.html#importlib.resources.abc.TraversableResources))

Looks like need to use `importlib.resources.abc.Traversable`.
