### PR TITLE
i2ctarget: Add deinit() to I2CTargetRequest; remove close()

### LINKED ISSUE #10362: i2ctarget error with missing deinit for request
Since #10040 (9.2.5 and after) this happens with the i2ctarget example:

```py
code starting...
9.789: INFO - read request to address '0x40'
Traceback (most recent call last):
  File "code.py", line 38, in <module>
AttributeError: 'I2CTargetRequest' object has no attribute 'deinit'
```

This is apparently because the new default `__exit__` requires the presence of `deinit` in the object's dictionary, and `I2CTargetRequest` doesn't have one. It has a `close()` though, (which incidentally doesn't have a docstring).

Should `I2CTargetRequest` have a `deinit()` that calls `common_hal_i2ctarget_i2c_target_close()` and also maybe remove the `close()` method ?

https://github.com/adafruit/circuitpython/blob/d88fe106476561c6cc25fdea26490fc9af92a44b/shared/runtime/context_manager_helpers.c#L14

https://github.com/adafruit/circuitpython/blob/d88fe106476561c6cc25fdea26490fc9af92a44b/shared-bindings/i2ctarget/I2CTarget.c#L395-L405

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #10362.

Removes visible `I2CTargetRequest.close()` method. Adds `I2CTargetRequest.deinit()`. Does `close()` and `deinit()` in `I2CTargetRequest.__exit__()`. Makes `I2CTargetRequest` have a finalizer: `__del__()` calls `deinit()`.

I tried testing with the more extensive example in the `I2CTarget` documentation, which tries to write and then read a value to an I2C register. It did not work, but I could not get that example to work with 8.2.9 or 9.2.3 either.

@Neradoc if you or someone else would like to test this with some previously-working code, I would be grateful.

### CODE REVIEW

**Comment by Neradoc** [comment]
The following test code triggers the issue in 9.2.7 and works as expected with this PR.

Controller code (running on a tiny2350)
```py
import busio
import board
import random
import time
from adafruit_bus_device.i2c_device import I2CDevice

i2c = busio.I2C(board.SCL, board.SDA)
device = I2CDevice(i2c, 0x40)
buffer = bytearray(1)

while True:
    try:
        with device:
            device.readinto(buffer)
            print(f"device responded with #{buffer[0]:02X}")
        time.sleep(1)

        with device:
            buffer[0] = random.randint(0, 255)
            device.write(buffer)
            print(f"wrote to device: #{buffer[0]:02X}")
        time.sleep(1)

    except OSError: # target resetting or in error
        time.sleep(1)
```
Target code (pro micro 2040) - that's the code being tested.
```py
import board
from i2ctarget import I2CTarget

memory = 0x55
with I2CTarget(board.SCL, board.SDA, (0x40,)) as device:
    while True:
        i2c_target_request = device.request()
        if not i2c_target_request:
            continue

        with i2c_target_request:
            if i2c_target_request.is_read:
                print(f"read request: #{memory:02X}")
                buffer = memory.to_bytes(1)
                i2c_target_request.write(buffer)
            else:
                data = i2c_target_request.read(1)
                print(f"write request: #{data[0]:02X}")
                memory = data[0]
```

Could we have the call to `common_hal_i2ctarget_i2c_target_close` in deinit ? It is possible (though ill advised) to not use the context manager and call deinit manually, in which case I believe close wouldn't be called.
And then we could remove the custom `__exit__`.

**Comment by dhalbert** [comment]
> Could we have the call to `common_hal_i2ctarget_i2c_target_close` in deinit ? It is possible (though ill advised) to not use the context manager and call deinit manually, in which case I believe close wouldn't be called.
> And then we could remove the custom `__exit__`.

I considered that, but wasn't sure if there was another use case. But I think not. I'll do that, yes, thanks.

**Review by Neradoc — APPROVED** [review]
Runs fine, looks good.

**Comment by dhalbert** [comment]
I will open a separate issue to fix the example.
